apiVersion: v2
name: qdrant
description: Qdrant - Vector Database for the next generation of AI applications.
home: https://qdrant.tech
sources:
  - https://github.com/qdrant/qdrant
  - https://github.com/qdrant/qdrant-helm
keywords:
  - vector database
maintainers:
  - name: qdrant
    email: info@qdrant.com
    url: https://github.com/qdrant
icon: https://qdrant.github.io/qdrant-helm/logo_with_text.svg
type: application
version: 1.16.3
appVersion: v1.16.3
annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: |
    - kind: added
      description: Update Qdrant to v1.16.3
    - kind: added
      description: Add support for global additional labels
      links:
        - name: GitHub Pull Request
          url: https://github.com/qdrant/qdrant-helm/pull/424
    - kind: added
      description: Add support for setting persistent volume claim labels
      links:
        - name: GitHub Pull Request
          url: https://github.com/qdrant/qdrant-helm/pull/418
    - kind: fixed
      description: Add the ability to set minReadySecond
      links:
        - name: GitHub Pull Request
          url: https://github.com/qdrant/qdrant-helm/pull/417
