{{- if .Values.metrics.serviceMonitor.enabled }}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
{{- with .Values.metrics.serviceMonitor.additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "qdrant.fullname" . }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
      path: {{ .Values.metrics.serviceMonitor.targetPath }}
      port: {{ .Values.metrics.serviceMonitor.targetPort }}
      scheme: http
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "qdrant.labels" . | nindent 6 }}
{{- end }}
